// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: mysvr.proto

package mysvr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MysvrServiceClient is the client API for MysvrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MysvrServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type mysvrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMysvrServiceClient(cc grpc.ClientConnInterface) MysvrServiceClient {
	return &mysvrServiceClient{cc}
}

func (c *mysvrServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/mysvr.MysvrService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MysvrServiceServer is the server API for MysvrService service.
// All implementations must embed UnimplementedMysvrServiceServer
// for forward compatibility
type MysvrServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	mustEmbedUnimplementedMysvrServiceServer()
}

// UnimplementedMysvrServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMysvrServiceServer struct {
}

func (UnimplementedMysvrServiceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedMysvrServiceServer) mustEmbedUnimplementedMysvrServiceServer() {}

// UnsafeMysvrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MysvrServiceServer will
// result in compilation errors.
type UnsafeMysvrServiceServer interface {
	mustEmbedUnimplementedMysvrServiceServer()
}

func RegisterMysvrServiceServer(s grpc.ServiceRegistrar, srv MysvrServiceServer) {
	s.RegisterService(&MysvrService_ServiceDesc, srv)
}

func _MysvrService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysvrServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mysvr.MysvrService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysvrServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MysvrService_ServiceDesc is the grpc.ServiceDesc for MysvrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MysvrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mysvr.MysvrService",
	HandlerType: (*MysvrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _MysvrService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mysvr.proto",
}
