version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '$PORT:80'

  myapp:
    build:
      context: ../build/dev
    volumes:
      - ../:/app
    working_dir: /app/cmd/myapp
    expose:
      - '$MYAPP_PORT'
    environment:
      MYAPP_PORT: $MYAPP_PORT
      MYAPP_GRPC_MYSVR_ADDR: mysvr:$MYSVR_PORT
    deploy:
      replicas: $MYAPP_REPLICAS
    depends_on:
      - mysvr

  mysvr:
    build:
      context: ../build/dev
    volumes:
      - ../:/app
    working_dir: /app/cmd/mysvr
    expose:
      - '$MYSVR_PORT'
    environment:
      MYSVR_PORT: $MYSVR_PORT
    deploy:
      replicas: $MYSVR_REPLICAS