// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package ports

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AddParams defines parameters for Add.
type AddParams struct {
	A *int `json:"a,omitempty"`
	B *int `json:"b,omitempty"`
}

// HelloParams defines parameters for Hello.
type HelloParams struct {
	Name *string `json:"name,omitempty"`
}
